version: '3'
services:
  tasks:
    build:
      context: .
      dockerfile: Dockerfile.tasks
    command: /var/app/tasks-start.sh --processes 1 --watch ./pixie_plugin
    stdin_open: true
    tty: true
    volumes:
      - ./:/var/app
    environment:
      - ENVIRONMENT=development
      - REDIS_URL=redis://redis:6379
      - REDIS_QUEUE_CHECKIN_ENDPOINT=http://web:8080/healthcheck/worker-checkin
      - NEW_RELIC_APP_NAME=pixie_plugin Tasks ($USER dev environment)
      - PIXIE_API_TOKEN=$PIXIE_API_TOKEN
      - PIXIE_CLUSTER_ID=$PIXIE_CLUSTER_ID
      - NR_INSERT_KEY=$NR_INSERT_KEY
      - NR_ACCOUNT_ID=$NR_ACCOUNT_ID
  redis:
    image: redis:5-alpine
